// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2jq6u7N7XOeFy_mVrAUky-JOrEtLHJf4',
    appId: '1:49000036332:web:a245a34dfd1080ce6f32c9',
    messagingSenderId: '49000036332',
    projectId: 'mano176-wonderwall',
    authDomain: 'mano176-wonderwall.firebaseapp.com',
    storageBucket: 'mano176-wonderwall.appspot.com',
    measurementId: 'G-4K1TDDYV46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8_P7aLsmxxyNZeGnMWwZqNxlwUVZ0eR8',
    appId: '1:49000036332:android:d450a62bf73fd4416f32c9',
    messagingSenderId: '49000036332',
    projectId: 'mano176-wonderwall',
    storageBucket: 'mano176-wonderwall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADVat2RYjZxeJXe1MAX79x5yRvz0LqCdc',
    appId: '1:49000036332:ios:84676003b47b161c6f32c9',
    messagingSenderId: '49000036332',
    projectId: 'mano176-wonderwall',
    storageBucket: 'mano176-wonderwall.appspot.com',
    iosBundleId: 'com.mano176.wonderwall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADVat2RYjZxeJXe1MAX79x5yRvz0LqCdc',
    appId: '1:49000036332:ios:84676003b47b161c6f32c9',
    messagingSenderId: '49000036332',
    projectId: 'mano176-wonderwall',
    storageBucket: 'mano176-wonderwall.appspot.com',
    iosBundleId: 'com.mano176.wonderwall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2jq6u7N7XOeFy_mVrAUky-JOrEtLHJf4',
    appId: '1:49000036332:web:9e1f0617fab2a7dd6f32c9',
    messagingSenderId: '49000036332',
    projectId: 'mano176-wonderwall',
    authDomain: 'mano176-wonderwall.firebaseapp.com',
    storageBucket: 'mano176-wonderwall.appspot.com',
    measurementId: 'G-M8ZLLZ1BYG',
  );
}
